# Configuration for Codecov
# https://docs.codecov.com/docs/codecovyml-reference

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true

comment:
  layout: "header, diff, flags, components, footer"
  behavior: default
  require_changes: false

ignore:
  - "**/*_test.go"
  - "**/testdata/**"
  - "cmd/**"
  - "internal/cli/update_readme.go"
